### ISSUE TITLE
issue when generating ground truth for direction map and WTN

### ISSUE THREAD

**Issue by bill2239** [min2209/dwt#9]
I tried to run the batch_generate_cityscapes.m to generate the ground truth mat. 
I encountered the following error in generate_GT_cityscapes_unified.m
Error using repmat
Too many input arguments.

Error in generate_GT_cityscapes_unified (line 13)
    dir_map = repmat(depth_map, 1, 1, 2);
ps. I used Matlab 2013a
Can someone please tell me what repmat(depth_map, 1, 1, 2); is intended to do? 
Also, could someone tell me what 'depth_map', 'dir_map', 'weight_map', 'edge_map' represent? thanks. I suppose dir_map is direction of distance transform.

**Comment by bill2239** [comment]
does 'depth_map' represent GT watershed energy and 'dir_map' represent direction map of distance transform?

**Comment by min2209** [comment]
Hi,

yes, that is right. 

repmat is supposed to repeat the input matrix by 1, 1, 2 times over axis 1, 2, 3, respectively.

Thanks!

**Comment by bill2239** [comment]
thanks! I was able to solve the remat issue by using dir_map = repmat(depth_map, [1, 1, 2]);
I have another question is that: what is keys trying to do, is keys = [26000, 26999;
    24000, 24999,
    25000, 25999,
    32000, 32999,
    33000, 33999,
    27000, 27999,
    28000, 28999,
    31000, 31999]; 
randomly chosen or these values are chosen specific for cityscape dataset? thanks

**Comment by min2209** [comment]
yes, those are specific to cityscapes. in particular, cityscapes encodes their instance segmentation image as class id * 1000 + instance id, so that for example pedestrian (class 24) have instance labels 24000, 24001, etc.

**Comment by bill2239** [comment]
I got it. thank you!
